/*
 * EditarExcepciones.java
 *
 * Created on 9 de abril de 2006, 19:09
 */

package nombrespropios;
import javax.swing.*;
import java.util.*;
import java.io.*;
/**
 *
 * @author  Victor del Canto
 */
public class EditarExcepciones extends javax.swing.JFrame {

    public static DefaultListModel lsexc=new DefaultListModel();
    public static EditorNP jlistexc= new EditorNP();
    /** Creates new form EditarExcepciones */
    public EditarExcepciones() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        añadir = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        Excepcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITOR DE EXCEPCIONES");
        setFocusCycleRoot(false);
        setFocusTraversalPolicy(null);
        setFocusable(false);
        añadir.setText("A\u00f1adir");
        añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 38, 0);
        getContentPane().add(añadir, gridBagConstraints);

        eliminar.setText("Eliminar");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 11, 3, 35);
        getContentPane().add(eliminar, gridBagConstraints);

        cerrar.setText("Cerrar");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 38, 0);
        getContentPane().add(cerrar, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFocusCycleRoot(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(4450, 2200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(250, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 200));
        jList1.setModel(lsexc);
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        Excepcion.setColumns(20);
        Excepcion.setMinimumSize(new java.awt.Dimension(45, 22));
        Excepcion.setPreferredSize(new java.awt.Dimension(226, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 34, 0, 20);
        getContentPane().add(Excepcion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        getContentPane().add(error, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-413)/2, (screenSize.height-327)/2, 413, 327);
    }
    // </editor-fold>//GEN-END:initComponents

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        int indic=jList1.getSelectedIndex(); // Posicion de JList seleccionado       
        if (indic!=-1){ // se ha seleccionado un elemento
            jlistexc.quitarSet(jlistexc.ListaExcepciones,jList1.getSelectedValue().toString()); //Quitar del conjunto Excepciones
            lsexc.removeElementAt(indic);   //Quitar de JList
        }
    }//GEN-LAST:event_eliminarMouseClicked

    private void añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirMouseClicked
        error.setText(" "); //Borra el indicador del error
        String elemento=Excepcion.getText(); //toma la palabra tecleada
        String inicial=elemento.substring(0,1);
        String cadenaMAY=elemento.toLowerCase();
        String INICMAY=cadenaMAY.substring(0,1);
        if (inicial.equals(INICMAY)==false) {//Comprueba que empieza por mayusculas
            jlistexc.añadirSet(jlistexc.ListaExcepciones,elemento);//añade la palabra al conjunto
            lsexc.clear();//borra la pantalla
            creaJLIST();// se vuelve a crear y mostrar la JList para que salga ordenada
        } else {
            error.setText("No es un Nombre Propio. No empieza por mayusculas");
        }
    }//GEN-LAST:event_añadirMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        try {   //Guarda el contenido de la JList en el fichero Excepciones.txt
            BufferedWriter out= new BufferedWriter(new FileWriter("Excepciones.txt"));
            out.write(jlistexc.ListaExcepciones.toString());
            out.close();
        }catch (IOException e){
        }
        lsexc.clear();  //Limpia el contenido de JList
        this.dispose(); //Cierra y 
        this.setVisible(false); //oculta la ventana
    }//GEN-LAST:event_cerrarMouseClicked

        
        public static void creaJLIST() {    //Pone los elemetos del conjunto Excepciones en el Jlist
        Iterator c=jlistexc.ListaExcepciones.iterator();
        while (c.hasNext()==true) {
            lsexc.addElement(c.next());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                creaJLIST();
                new EditarExcepciones().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Excepcion;
    private javax.swing.JButton añadir;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
