/*
 * EditarNPConocidos.java
 *
 * Created on 9 de abril de 2006, 20:23
 */

package nombrespropios;
import javax.swing.*;
import java.util.*;
import java.io.*;
/**
 *
 * @author  Victor del Canto
 */
public class EditarNPConocidos extends javax.swing.JFrame {
    public static DefaultListModel lscono=new DefaultListModel();
    public static EditorNP jlistcon= new EditorNP();    
    /** Creates new form EditarNPConocidos */
    public EditarNPConocidos() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        añadir = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        Nombre = new javax.swing.JTextField();
        error = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDITAR NP CONOCIDOS");
        setFocusCycleRoot(false);
        añadir.setText("A\u00f1adir");
        añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(añadir, gridBagConstraints);

        eliminar.setText("Eliminar");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(eliminar, gridBagConstraints);

        cerrar.setText("Cerrar");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(cerrar, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setInheritsPopupMenu(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(4450, 2200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(450, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(250, 200));
        jList1.setModel(lscono);
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 11;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        Nombre.setColumns(20);
        Nombre.setMinimumSize(new java.awt.Dimension(60, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 10, 10);
        getContentPane().add(Nombre, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        getContentPane().add(error, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-450)/2, (screenSize.height-300)/2, 450, 300);
    }
    // </editor-fold>//GEN-END:initComponents

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        int indic=jList1.getSelectedIndex();    //Posicion de JList seleccionado       
        if (indic!=-1){     //se ha seleccionado un elemento
            jlistcon.quitarSet(jlistcon.ListaConocidos,jList1.getSelectedValue().toString());   //quitar del conjunto Conocidos
            lscono.removeElementAt(indic);            //quitar de JList
        }
    }//GEN-LAST:event_eliminarMouseClicked

    private void añadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirMouseClicked
        error.setText(" ");     //borra el indicador de error
        String elemento=Nombre.getText();   //toma la palabra tecleada
        String inicial=elemento.substring(0,1);
        String cadenaMAY=elemento.toLowerCase();
        String INICMAY=cadenaMAY.substring(0,1);
        if (inicial.equals(INICMAY)==false) {   //Comprueba que empieza por mayusculas
            jlistcon.añadirSet(jlistcon.ListaConocidos,elemento);//añade la palabra al conjunto Conocidos
            lscono.clear();  //borra la pantalla
            creaJLIST();    // se vuelve a crear y mostrar la JList para que salga ordenada
        } else {
            error.setText("No es un Nombre Propio. No empieza por mayusculas");
        }
    }//GEN-LAST:event_añadirMouseClicked

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        try {       //guarda el contenido de la JList en el fichero Conocidos.txt
            BufferedWriter out= new BufferedWriter(new FileWriter("Conocidos.txt"));
            out.write(jlistcon.ListaConocidos.toString());
            out.close();
        }catch (IOException e){
        }
        lscono.clear();      //limpia el contenido de la JList
        this.dispose();     //cierra y
        this.setVisible(false);     //oculta la ventana
    }//GEN-LAST:event_cerrarMouseClicked

        public static void creaJLIST() {    //Pone los elementos del conjunto Conocidos en un JList
            Iterator c=jlistcon.ListaConocidos.iterator();
        while (c.hasNext()==true) {
            lscono.addElement(c.next());
        }
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                creaJLIST();                
                new EditarNPConocidos().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton añadir;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel error;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
