/*
 * ExplorarArchivo.java
 *
 * Created on 6 de abril de 2006, 17:10
 */

package nombrespropios;

/**
 *
 * @author  Victor del Canto
 */
public class ExplorarArchivo extends javax.swing.JFrame {
    
    /** Creates new form ExplorarArchivo */
    public ExplorarArchivo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abrir texto");
        getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
     public String fichero(ExplorarArchivo explordialog) {
            int returnVal=jFileChooser1.showOpenDialog(explordialog);   //valor asignado de abrir o cancelar
            if (returnVal==jFileChooser1.APPROVE_OPTION) {      //si se ha pulsado abrir
            String nombre=new String(jFileChooser1.getSelectedFile().getPath());    //devuelve el nombre de archivo a                   
                return(nombre);     //tratar con su trayectoria 
            } else {
                return("sin fichero");      //si se ha pulsado cancelar
            }
        }
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExplorarArchivo().setVisible(true);
            }
           
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
    
}
