/*
 * ner.java
 *
 * Created on 3 de abril de 2006, 18:15
 */

package nombrespropios;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.text.*;
/**
 *
 * @author  Victor del Canto
 */
public class ner extends javax.swing.JFrame {
    
    
    public static EditorNP editorGeneral=new EditorNP();
    public static String g= new String();
    public static boolean verde=false;
    public static boolean rojo=false;
    public static boolean rojoaux=false;
    public static boolean verdeaux=false;
    public static StyledDocument doc;
    /** Creates new form ner */
    public ner()  {
        initComponents();
        this.setSize(782,500);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Explorar = new javax.swing.JPopupMenu();
        editarexcepciones = new javax.swing.JButton();
        editarnpconocidos = new javax.swing.JButton();
        fichero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Explora = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        marcardesconocidos = new javax.swing.JCheckBox();
        marcarconocidos = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        listarconocidos = new javax.swing.JButton();
        listardesconocidos = new javax.swing.JButton();

        Explorar.setInvoker(Explora);

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("programa");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        editarexcepciones.setText("Editar Excepciones");
        editarexcepciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarexcepcionesMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(editarexcepciones, gridBagConstraints);

        editarnpconocidos.setText("Editar NP Conocidos");
        editarnpconocidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarnpconocidosMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(editarnpconocidos, gridBagConstraints);

        fichero.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(fichero, gridBagConstraints);

        jLabel2.setText("Fichero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel2, gridBagConstraints);

        Explora.setText("Explorar");
        Explora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExploraMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        getContentPane().add(Explora, gridBagConstraints);

        abrir.setText("Abrir");
        abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        getContentPane().add(abrir, gridBagConstraints);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(new javax.swing.border.EtchedBorder());
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(625, 550));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(175, 150));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(225, 250));
        jTextPane1.setDocument(jTextPane1.getStyledDocument());
        jScrollPane2.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        marcardesconocidos.setText("Marcar NP Desconocidos (rojo)");
        marcardesconocidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marcardesconocidosMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        getContentPane().add(marcardesconocidos, gridBagConstraints);

        marcarconocidos.setText("Marcar NP Conocidos (verde)");
        marcarconocidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marcarconocidosMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        getContentPane().add(marcarconocidos, gridBagConstraints);

        jLabel1.setText("Listar Np reconocidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        getContentPane().add(jLabel1, gridBagConstraints);

        listarconocidos.setText("Conocidos");
        listarconocidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarconocidosMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        getContentPane().add(listarconocidos, gridBagConstraints);

        listardesconocidos.setText("ListarNPDesconocidos");
        listardesconocidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listardesconocidosMouseClicked(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        getContentPane().add(listardesconocidos, gridBagConstraints);

        setBounds(120, 90, 400, 300);
    }
    // </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    actualiza();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    actualiza();
    }//GEN-LAST:event_formWindowActivated

    private void marcarconocidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcarconocidosMouseClicked
// Con la pulsacion del boton izquierdo del raton cambia el estado de verde (booleano) 
    if ((evt.getModifiers() & java.awt.event.InputEvent.BUTTON1_MASK)!=0) {
/*        if (g.equals(null)==false){ //existe un archivo que abrir   */     
        verde=!verde;
        actualiza();     //actualiza el texto en la ventana
    }
    }//GEN-LAST:event_marcarconocidosMouseClicked

    private void marcardesconocidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcardesconocidosMouseClicked
// Con la pulsacion del boton izquierdo del raton cambia el estado de rojo (booleano)
    if ((evt.getModifiers() & java.awt.event.InputEvent.BUTTON1_MASK)!=0) {
/*        if (g.equals(null)==false){ //existe un archivo que abrir*/
        rojo=!rojo;
        actualiza();     //actualiza el texto en la ventana
    }
    }//GEN-LAST:event_marcardesconocidosMouseClicked

    private void abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMouseClicked
        g=fichero.getText();//toma el nombre del archivo seleccionado
        actualiza(); // actualiza el panel (metodo publico)
    }//GEN-LAST:event_abrirMouseClicked

    private void listardesconocidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listardesconocidosMouseClicked
        ListarNPdesconocidos lisdes=new ListarNPdesconocidos(); //Se crea el objeto
        lisdes.lsdes.clear();   //Inicializacion
        lisdes.creaJLIST();     //y 
        lisdes.setVisible(true); //activacion 
    }//GEN-LAST:event_listardesconocidosMouseClicked

    private void listarconocidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarconocidosMouseClicked
        ListarNPconocidos liscon=new ListarNPconocidos(); //Se crea el objeto
        liscon.lscon.clear();   //Inicializacion
        liscon.creaJLIST();     //y         
        liscon.setVisible(true); //activacion
    }//GEN-LAST:event_listarconocidosMouseClicked

    private void editarnpconocidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarnpconocidosMouseClicked
        EditarNPConocidos edcon= new EditarNPConocidos(); //Se crea el objeto
        edcon.lscono.clear();   //Inicializacion
        edcon.creaJLIST();     //y            
        edcon.setVisible(true); //activacion
        
    }//GEN-LAST:event_editarnpconocidosMouseClicked

    private void ExploraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExploraMouseClicked
        ExplorarArchivo explordialog = new ExplorarArchivo(); //Se crea el objeto
        explordialog.setVisible(true); //activacion
        String sg=explordialog.fichero(explordialog);   //fichero escogido
        fichero.setText(sg);    //se muestra en la pantalla
        explordialog.setVisible(false);     //ocultacion       
        remove(explordialog);        //y cierre
    }//GEN-LAST:event_ExploraMouseClicked

    private void editarexcepcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarexcepcionesMouseClicked
        EditarExcepciones edex= new EditarExcepciones(); //Se crea el objeto
        edex.lsexc.clear();   //Inicializacion
        edex.creaJLIST();     //y                
        edex.setVisible(true); //activacion
    }//GEN-LAST:event_editarexcepcionesMouseClicked
    
    public static void limpiarPanel() throws BadLocationException {
        if (doc.equals(null)==false) {  // Si el panel contiene texto
        doc.remove(0,doc.getLength()); //se borra todo
        //escritura(" ",3,doc);
    }
    }
    
    public static void escritura(String cadena,int version,StyledDocument doc)throws BadLocationException {
//para el rojo        
        Style estiloRojo = jTextPane1.addStyle(null,null);
        StyleConstants.setForeground(estiloRojo,Color.red);
//para el verde
        Style estiloVerde = jTextPane1.addStyle(null,null);
        StyleConstants.setForeground(estiloVerde,Color.green);
//para el negro
        Style estiloNegro = jTextPane1.addStyle(null,null);
        StyleConstants.setForeground(estiloNegro,Color.black);
        
        switch(version) {
            case 1:
                doc.insertString(doc.getLength(),cadena,estiloVerde);
                break;
            case 2:
                doc.insertString(doc.getLength(),cadena,estiloRojo);
                break;
            case 3:
                doc.insertString(doc.getLength(),cadena,estiloNegro);
                break;                
            default:
                doc.insertString(doc.getLength(),cadena,estiloNegro);
        }
    }

    
    public static void CrearArchivo(String nombre) throws IOException {
        BufferedReader arch=new BufferedReader(new FileReader(nombre)); //Se abre un archivo
        if (arch.read()==-1) {      //si no existia 
            new File(nombre).createNewFile(); //se crea nuevo
        }
    }

    public void actualiza() {
        try {
            doc=jTextPane1.getStyledDocument(); //estilo de escritura rojo, verde o negro
            limpiarPanel(); // se borra el panel (para actualizaciones)            
            if (g.equals("")==false){ //existe un archivo que abrir
                editorGeneral.limpiar();
                editorGeneral.CrearLista();
                int elem=editorGeneral.lista.size();    // numero de tokens del archivo
                for (int x=0;x<(elem);x++) {
                // Se escribe en el panel cada token segun le corresponda este o no activada su marca    
                    if ((editorGeneral.ListaConocTexto.contains(x)==true)&&(verde==true)) {
                        escritura(editorGeneral.lista.get(x).toString(),1,doc);
                    }else if ((editorGeneral.ListaDesconocTexto.contains(x)==true)&&(rojo==true)) {
                        escritura(editorGeneral.lista.get(x).toString(),2,doc);
                    }else { escritura(editorGeneral.lista.get(x).toString(),3,doc);

                    }
                }                
            }else {
            editorGeneral.limpiar();
            }

        }catch(IOException e){
        JFrame err=new JFrame();
        ErrorFichero error=new ErrorFichero(err,true);
        error.setVisible(true);
        }catch (BadLocationException e){
        System.out.println("error BadLocation");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
            // Toma la apariencia del sistema 
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            //Se crean los archivos Excepciones.txt y Conocidos.txt si no existian
                CrearArchivo("Excepciones.txt");
                CrearArchivo("Conocidos.txt");
            //Se añaden los contenidos de Excpcion.txt y Conocidos.txt a sus conjuntos correspondientes
                 editorGeneral.CrearSet("Excepciones.txt",editorGeneral.ListaExcepciones);
                editorGeneral.CrearSet("Conocidos.txt",editorGeneral.ListaConocidos);
                } catch (Exception e) {
                } 
                
                new ner().setVisible(true);
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Explora;
    private javax.swing.JPopupMenu Explorar;
    private javax.swing.JButton abrir;
    private javax.swing.JButton editarexcepciones;
    private javax.swing.JButton editarnpconocidos;
    private javax.swing.JTextField fichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton listarconocidos;
    private javax.swing.JButton listardesconocidos;
    private javax.swing.JCheckBox marcarconocidos;
    private javax.swing.JCheckBox marcardesconocidos;
    // End of variables declaration//GEN-END:variables
    
}
